# [D+59] 자바프로그래밍5

### 예외란? (Exception)

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FdwuH0D%2FbtrTRoOChmj%2FqIP1aTGxlL3x7D7kLpv18K%2Fimg.png" width="75%"/>

\- 프로그램의 실행시 사용자 또는 시스템의 문제로 인해 어플리케이션이 대응하지 못하는 비정상적 상황<br>
\- 코드의 문제가 아니라 Run-time에 발생하는 비정상적 상황<br>
\- 예외는 H/W적 처리방식과 S/W적 처리방식이 있으나 JVM의 경우 별도로 처리 로직이 존재하지 않는한 종료 처리한다. => 더이상 JAVA실행 코드의 무결성을 지킬 수 없다고 판단하기 때문이다.<br><br>

### • 예외의 종류

\- java.lang.ArithmeticException : 수학 연산의 예외<br>
\- java.util.InputMismatchException : Scanner를 통한 값의 입력 예외<br>
\- 예외가 발생하면 예외 발생에 따른 예외 클래스의 인스턴스를 생성하고 프로그래머가 일을처리할 경우 JVM은 무결성이 지켰다고 간주된다.<br><br>

### • 예외 처리

#### <b>try-catch 문</b>

```
try 
{
	// 예외 발생 예상 영역
}

catch (Exception name)
{
	// 예외 처리 영역
}

// 예외처리 이후 실행지점
```

\- 예외를 처리하기 위한 문법으로 try에서 발생한 예외를 catch영역에서 처리하는 방식이다.<br>
\- 이때 주의해야할 것은 예외가 발생해서 예외를 해결하겠다가 아니라 발생된 예외에 대해 사용자에게 알려주는 처리를 하겠다는 의미이다.<br><br>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fmw2on%2FbtrTYBFnSkv%2FHKnhNadoo9V8ouDKvLVrZ1%2Fimg.png" width="70%"/><br><br>

#### <b>finally</b>

```
try
{
	...
}

catch(Exception e)
{
	...
}

finally
{
	... // try가 실행되면 무조건 실행
}
```

\- try구문이 실행된 경우, 최종적으로 실행할 구문을 처리하기 위한 키워드 이다.<br><br>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FkEkta%2FbtrTXMmQ7Ac%2FpRvqrQakU3akl1yeAZKIz1%2Fimg.png" width="100%"/><br><br>

### • 예외처리의 범위

#### <b>예외처리의 범위</b>

예외처리의 범위는 try로 블록처리를 한다. <br>
이때 try블록의 범위는 아래와 같은 기준으로 처리한다.<br><br>

> <b>try블록의 범위</b><br>
> 1 > 예외가 발생하는 코드 범위<br>
> 2 > 예외가 발생했을 경우 영향을 받는 코드의 범위<br>

만약 try로 다 묶어버리게 되면 JVM의 명령이 비대해지고 버거워져서 느려지게 되므로 최소한으로 묶어야 한다.<br>
그렇다고 너무 최소한이 아닌 C에도 문제가 발생될 수도 있기 때문에 그것도 고려해주어서 묶어주어야 한다.<br><br>

연산을 기준으로 묶는 거지 예외별로 묶는 것이 아니라는 것을 명심하길 바란다.<br><br>

#### <b>둘 이상의 예외 발생</b>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbSkfKm%2FbtrTZAsR6cw%2FKGcpVsnqrgTXdMs4GUrnI0%2Fimg.png" width="100%"/>

하나의 try블록에서 만약 두개 이상의 예외가 발생할 가능성이 있는 경우에 각각의 예외에 대한 catch문을 작성하도록 한다.<br><br>

### • 예외 던지기

#### <b>Throwable 클래스</b>

\- 예외 처리의 최상위 클래스로 모든 예외처리 클래스는 Throwable 클래스를 상속 받는다.<br>
\- getMessage(), printStackTrace() 등의 기능도 Throwable의 메소드 이다.<br>
\- Throwable로 에러처리를 할때 주의해야할 점은 모든 클래스의 예외 클래스를 받을 수 있기때문에 만약 상단에 Throwable로 처리해줄 경우 뒤에오는 catch문이 데드코드가 되어버리므로 가급적 사용을 피하도록 해야한다.<br><br>

#### <b>다양한 예외 클래스</b>

\- ArrayIndexOutOfBounds : 배열의 잘못된 인덱스 접근<br>
\- ClassCastException : 허용 불가능한 형변환을 강제로 진행<br>
\- NullPointerException : Null이 저장된 참조변수의 접근<br><br>

### • 예외 처리 심화

#### <b>예외 클래스의 분류</b>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcOimbb%2FbtrTSxc9xvR%2FtoBj1xT1YWHeXOK6glOko0%2Fimg.png" width="70%"/>

<b>Error</b><br>
\- 비검사 예외 클래스<br>
\- 어플리케이션의 진행이 불가능한 상태이다.<br>
\- 임의의 상속이 불가하다.<br>
\- VirtualMachineError, IOError<br><br>

<b>RuntimeException</b><br>
\- 일반적으로 어플리케이션에서 예외처리를 진행할 수 있는 클래스이다.<br><br>

<b>Exception</b><br>
\- 검사 예외 클래스<br>
\-  검사를 할 수 있는 것이지 해결가능한 것은 아니다.<br><br>

#### <b>java.io.IOException</b>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fnysbr%2FbtrT3oFsKy8%2FkCykXVvuaaD25UxCcUms11%2Fimg.png" width="70%"/>

\- try문을 지워보면 컴파일 오류가 발새오디는데 이는 IOException은 반드리 검사를 해야하는 Exception에서 상속된 예외처리이기 때문에 반드시 try문으로 처리해줘야 한다.<br><br>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcmfZfA%2FbtrTR0fz5ga%2FQL3tEwOIKrVCbnuDZsP2GK%2Fimg.png" width="100%"/>

\- 만약 main이 아닌 메소드 내에서 IOException이 발생할 가능성이 있는 코드가 존재할 경우 throws 키워드를 통해 예외를 명시적으로 표시해야한다.<br><br>

### • 사용자 정의 예외

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcQzQUh%2FbtrTYC5q82p%2FG2DzUs80NkqvgW0T2PmMo0%2Fimg.png" width="100%"/>

\- Exception을 상속받아 사용자 정의 예외를 만들어서 사용할 수 있다.<br>
\- 성능저하, 가독성 저하를 발생할 수 있다.<br><br>

### • try-with-resources

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbylR1e%2FbtrTUCZmjuI%2FOcjXShmAgsfLGrpxdlTnT1%2Fimg.png" width="100%"/>

일반적으로 file과 같은 resource는 Exception처리를 동반한다.<br>
이로인해 finally구문에서 코드가 복잡해지는 단점이 발생되는데 이를 해결하기 위해 try-with-resources 구문을 사용할 수 있다.

<br><br>

[티스토리 바로가기](https://onelight-stay.tistory.com/680)